// generate-modules.js
// Jalankan dengan: node generate-modules.js

const fs = require('fs');
const path = require('path');

// Daftar modul yang akan dibuat (tambah/edit di sini untuk modul baru)
const modules = [
    // Tab Dashboard
    { id: 'analytics', name: 'Analytics', icon: '📈', tab: 'dashboard' },
    { id: 'pengajuan', name: 'Pengajuan', icon: '📋', tab: 'dashboard' },
    { id: 'approval', name: 'Approval', icon: '✅', tab: 'dashboard' },
    { id: 'ai', name: 'AI', icon: '🤖', tab: 'dashboard' },
    { id: 'backup', name: 'Backup', icon: '💾', tab: 'dashboard' },
    { id: 'files', name: 'Files', icon: '📁', tab: 'dashboard' },

    // Tab Kerja
    { id: 'booking', name: 'Booking', icon: '📅', tab: 'kerja' },
    { id: 'k3', name: 'K3', icon: '⚠️', tab: 'kerja' },
    { id: 'sekuriti', name: 'Sekuriti', icon: '🛡️', tab: 'kerja' },
    { id: 'stok', name: 'Stok', icon: '📦', tab: 'kerja' },
    { id: 'maintenance', name: 'Maintenance', icon: '🔧', tab: 'kerja' },
    { id: 'asset', name: 'Asset', icon: '🏢', tab: 'kerja' },
    { id: 'janitor-indoor', name: 'Janitor In', icon: '🧹', tab: 'kerja' },
    { id: 'janitor-outdoor', name: 'Janitor Out', icon: '🌿', tab: 'kerja' },

    // Tab Dana
    { id: 'dana', name: 'Dana', icon: '💰', tab: 'dana' },
    { id: 'laporan', name: 'Laporan', icon: '📄', tab: 'dana' },

    // Tab Approval (kita gabung jadi satu modul)
    { id: 'approval', name: 'Approval', icon: '✅', tab: 'approval' },

    // Tab Files
    { id: 'files-k3', name: 'K3 Foto', icon: '🖼️', tab: 'files' },
    { id: 'files-spj', name: 'SPJ Foto', icon: '📸', tab: 'files' },

    // Tab Backup
    { id: 'backup-create', name: 'Create', icon: '💾', tab: 'backup' },
    { id: 'backup-restore', name: 'Restore', icon: '🔄', tab: 'backup' }
];

// Template module.js (contoh sederhana)
function getModuleTemplate(moduleId, moduleName) {
    return `// modules/${moduleId}/module.js
export function init() {
    const area = document.getElementById('module-content');
    if (!area) return;
    area.innerHTML = \`
        <div class="submodule-header" style="display: flex; align-items: center; gap: 1rem; margin-bottom: 1.5rem;">
            <button onclick="window.loadModule('commandcenter')" class="btn-crystal" style="background: rgba(255,255,255,0.1); border: none; padding: 0.5rem 1rem; border-radius: 12px; cursor: pointer;">
                ⬅️ Kembali
            </button>
            <h3 class="crystal-text" style="margin:0;">🚧 ${moduleName}</h3>
        </div>
        <div class="glass-card p-4">
            <p class="crystal-text">Modul ${moduleName} dalam pengembangan.</p>
        </div>
    \`;
}`;
}

// Buat folder dan file module.js untuk setiap modul
modules.forEach(mod => {
    const folderPath = path.join(__dirname, 'modules', mod.id);
    if (!fs.existsSync(folderPath)) {
        fs.mkdirSync(folderPath, { recursive: true });
        console.log(`📁 Folder dibuat: modules/${mod.id}`);
    }
    const filePath = path.join(folderPath, 'module.js');
    if (!fs.existsSync(filePath)) {
        fs.writeFileSync(filePath, getModuleTemplate(mod.id, mod.name));
        console.log(`📄 File dibuat: modules/${mod.id}/module.js`);
    } else {
        console.log(`⚠️ File sudah ada: modules/${mod.id}/module.js (lewatkan)`);
    }
});

// Bangun objek konfigurasi per tab
const config = {};
modules.forEach(mod => {
    if (!config[mod.tab]) config[mod.tab] = [];
    config[mod.tab].push({ id: mod.id, name: mod.name, icon: mod.icon });
});

// Tulis modules.config.js
const configPath = path.join(__dirname, 'modules.config.js');
const configContent = `// Auto-generated by generate-modules.js – JANGAN EDIT MANUAL
export default ${JSON.stringify(config, null, 2)};
`;
fs.writeFileSync(configPath, configContent);
console.log('✅ modules.config.js berhasil dibuat!');

console.log('\n🎉 SEMUA SELESAI! Jalankan perintah berikut untuk update:');
console.log('  node generate-modules.js');
